8 catalog api add a product
MisterPeModder/CyberMatos pull request #35
Opened 2023-04-10 18:12 UTC by MetalBrackets

2023-04-11 14:44 UTC, MisterPeModder requested changes
Il faut que te mettes les routes REST avec le prefixe `/api` (example : `GET /api/products`)

2023-04-11 14:44 UTC, MisterPeModder commented on README.md
> +5. Go to homepage -> https://localhost:34795
Mentionne le `.env.local`

2023-04-11 17:46 UTC, MisterPeModder requested changes

2023-04-11 17:46 UTC, MisterPeModder commented on README.md
> +2. Create a file `.en.local` with environment variable : `DATABASE_URL="mysql://user:password@127.0.0.1:3307/cybermatos?serverVersion=10.6.5-MariaDB"`
T'as fait une faute, c'est `.env.local`

2023-04-16 09:21 UTC, MetalBrackets commented on README.md
> +2. Create a file `.en.local` with environment variable : `DATABASE_URL="mysql://user:password@127.0.0.1:3307/cybermatos?serverVersion=10.6.5-MariaDB"`
![env](https://user-images.githubusercontent.com/46809929/232289261-0603f9e5-e34b-4fec-a5ab-ac986fb5f545.png)

2023-04-17 09:50 UTC, MisterPeModder approved these changes

2023-04-17 09:53 UTC, merged